# ASP.NET Core
# Build and test ASP.NET Core web applications targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core

pool:
    vmImage: 'Ubuntu 16.04'

variables:
    buildConfiguration: 'Release'
    imageVersion: latest

trigger: 
- master

steps:
- task: DotNetCoreInstaller@0
  displayName: Use .NET SDK 2.1.301
  inputs:
    version: '2.1.301'

- script: dotnet restore
  displayName: dotnet restore

- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: test
    projects: '**/*Tests.csproj'
    arguments: '--configuration $(buildConfiguration) --no-restore'

- script: |
    docker login -u $userId -p $pwd
    docker build -t $userId/$image:$version .
    docker push $userId/$image:$version
  displayName: docker build & push
  env:
    userId: $(Docker.UserId)
    image: $(Docker.Image)
    pwd: $(Docker.Password)
    version: $(imageVersion)
